fieldLayouts:
  e1049097-af03-4e7c-8300-bba34e797d87:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-31T13:11:53+00:00'
            elementCondition: null
            fieldUid: c4caefc2-cd31-47bf-b3d5-258093393a6c # Logo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95773708-b706-46ec-ac1a-55a59a5b593a
            userCondition: null
            warning: null
            width: 100
        name: Unternehmen
        uid: a91e63d8-7645-4b98-b41f-00e455c23492
        userCondition: null
handle: settings
name: Einstellungen
sortOrder: 1
