fieldLayouts:
  fda50950-b4ba-4d10-8d19-441b9245fd2b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7d109a97-df4e-499d-8200-ad8aac385a25 # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb2e612f-3e99-480e-8968-8c65c36de006
            userCondition: null
            warning: null
            width: 100
        name: Company
        uid: 822abdb8-b90f-4df9-8eaf-3f1cfd4994bd
        userCondition: null
handle: theme
name: Theme
sortOrder: 1
