altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  b37948d0-6a50-4bfd-aef2-3027fde78226:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-11T20:38:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 42575d2d-49a8-4867-922f-ae4cd1c35c9a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 59a51013-781d-428b-ad9e-7263a2466b6e
        userCondition: null
fs: documents
handle: documents
name: Dokumente
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
