altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  5b9bce74-3f93-4c49-a960-d0e35d9a0f4b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d8411fb9-4715-4957-9ed9-cd687206f6b7
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 21fd8a86-904c-4364-b9a0-663d276fc56a
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 866b81a8-4c9d-4d67-bc03-d061bbb282b7 # Hot
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf7c5577-3094-4d91-b60f-719daf385cc9
            userCondition: null
            warning: null
            width: 25
        name: Inhalt
        uid: bbb773de-3d00-4815-954d-54615e767d64
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: images
transformSubpath: _transforms
