altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  cea2aa59-287e-440f-bf04-2f51c1627e96:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-11T20:38:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 254f7c27-03d7-4a00-808b-7ffcfa6e815a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 874813c4-deab-4085-8f52-c0741e1abfc9
        userCondition: null
fs: img
handle: images
name: Bilder
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
