fieldLayouts:
  c0276d4a-c094-48f7-a2d5-3e9eb12dcf77:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 86c9d758-2e1e-4607-bf08-c5551482db89
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 581d5fd1-60a4-4529-916b-f68663b78685
        userCondition: null
fs: theme
handle: theme
name: Theme
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: _transforms
