color: null
fieldLayouts:
  1db3d3f8-fc12-406f-b3d5-5d06f2f681cc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-11T15:10:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 67115a03-ad4b-4ca1-b734-9c52a5843841
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dcef82a4-a33a-4cd9-a5b7-808aafa1ca81
        userCondition: null
handle: about
hasTitleField: true
icon: ''
name: 'Über uns'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
