fieldLayouts:
  e4baae65-27cf-4e30-afd7-37fbb7476ab3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1d0cf233-78d4-4262-8f57-2c84c18b488f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e7ee8b3a-be5d-47ce-b17d-cd53242423a9 # Blog Autor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5b4ad05-689a-4b94-9828-4972b4404167
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1eb88eb9-dc8e-4f62-a756-a0f68f2c4b56 # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 797ea6f3-d405-4471-b483-ae83b900ba2c
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 750837ec-effa-48a5-a56b-3eaff2214dfe
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 36fcb770-0e73-4e62-b21a-adbfcef75309 # Pagebuilder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba684182-1e9e-4a8c-8a08-49d54353b8c6
            userCondition: null
            warning: null
            width: 100
        name: Pagebuilder
        uid: cefda7ae-d640-417d-b426-564b8168a129
        userCondition: null
handle: blogEntries_default
hasTitleField: true
name: 'Blogbeiträge - Standard'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
