fieldLayouts:
  14543b45-71ad-4110-bf14-3ca81cacbdeb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5c0db7a6-61dd-449f-90ff-09c07d14f526
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 6f5f801f-29a0-43c0-bc49-e739d43c88c5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3494d0db-46d9-4ef4-b39d-4a5786b70db7 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31cecd7f-633d-4521-82d7-630140e37cbd
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 0cddcd72-3ca5-49fd-98ca-58881e6db126
        userCondition: null
handle: blogIndex
hasTitleField: false
name: 'Blog Index'
section: 67b66019-8059-4ac0-90c4-bc2a19df8329 # Blog Index
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
