color: orange
fieldLayouts:
  ef1b7327-50ed-4b73-a0c0-522189a61bc9:
    cardView:
      - 'layoutElement:330be84b-a10b-4b48-bf1f-9843cbb5a510'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-19T09:15:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2b85c689-60aa-49fd-bdd1-e1759edf92d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T09:18:00+00:00'
            elementCondition: null
            fieldUid: 60858e18-bc1b-4d81-ba23-8bd5ec4e4238 # Bildergalerie
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 330be84b-a10b-4b48-bf1f-9843cbb5a510
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fc0e8a66-8652-4c9b-9ef1-e981cfa3609c
        userCondition: null
handle: contentBlockImages
hasTitleField: true
icon: image
name: Bilder
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
