color: sky
fieldLayouts:
  a4bc8af9-81a2-409b-ab85-baa2d044763e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-23T06:29:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 89edd6ce-4383-4e60-ae25-d94637a55e4e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-23T06:40:59+00:00'
            elementCondition: null
            fieldUid: deec8964-03a8-4f19-94ac-4ee755da3bc1 # Button Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c97a2ab6-0be4-45b3-bd3c-8f4fd3650cc1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e1781166-1c97-40bb-aba3-f44cd4ca52c4
        userCondition: null
handle: contentBlockButton
hasTitleField: true
icon: link
name: Button
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
