fieldLayouts:
  547c31ae-a8f1-4bf2-bd59-3923c64a69ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 07e23876-6f01-4994-b90d-5c73ba0ce6e9
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8dfb6019-3f5b-4092-8a6c-606de9acd9af # Details
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d752e9dd-9f70-47d1-80f7-935a4784100a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6aee8eeb-9148-4f6c-9e02-6dba602de699 # Leistungskategorie
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a44843a3-c501-4214-8a89-e9257f728294
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 9d49afa0-3762-49d3-b0eb-3e8bce4d6be2
        userCondition: null
      -
        elementCondition:
          class: craft\elements\conditions\entries\EntryCondition
          conditionRules:
            -
              class: craft\fields\conditions\LightswitchFieldConditionRule
              fieldUid: 8dfb6019-3f5b-4092-8a6c-606de9acd9af # Details
              uid: b9e1ae5c-141b-4ceb-ab8e-7a8e923f6e56
              value: true
          elementType: craft\elements\Entry
          fieldContext: global
        elements:
          -
            elementCondition: null
            fieldUid: 36fcb770-0e73-4e62-b21a-adbfcef75309 # Pagebuilder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13e53226-49fa-4b72-88f7-2100c9a9b1a3
            userCondition: null
            warning: null
            width: 100
        name: Pagebuilder
        uid: 55337274-8aa1-4977-82d6-e123c198ccd8
        userCondition: null
handle: default
hasTitleField: true
name: Standard
section: 78940b12-1c99-4891-a34c-0ff8a86a5c8d # Leistungen
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
