fieldLayouts:
  f9c0722c-c76d-486f-a8df-0fd5dd432312:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 254b9998-72eb-4c90-a588-1c26a19baf3b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f881031-f799-41d6-8042-e8b92b581f44 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6968e6ba-c8cf-414e-9eb5-4ee5ae14f750
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f6b5071c-af6b-4660-8413-09076476a456 # Portfolio Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 352debbf-3088-4782-93fb-60c1eabd369e
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9d6cfeee-ff25-4e0d-b8cc-4d208c7fcb11 # Hintergrundfarbe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57178873-b154-4929-b708-3e7cf0b79720
            userCondition: null
            warning: null
            width: 50
        name: Inhalt
        uid: eb0ae1a7-c81a-412a-83d1-fce5222f0a91
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b52be6aa-63ba-43dd-a979-76ac8ac38f91 # URL Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9042f2e1-3c55-4b4f-b4c6-4a14f4b664b3
            userCondition: null
            warning: null
            width: 100
        name: Details
        uid: eaf37bd5-8602-4cca-85d5-a701f625fc8d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3494d0db-46d9-4ef4-b39d-4a5786b70db7 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2c16b54-fe98-4341-b775-5c2841da2903
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 81a20f3d-381b-45fa-9fd5-a661ef1f1b5a
        userCondition: null
handle: default
hasTitleField: true
name: Standard
section: 56f4efc4-b036-453e-84a3-fb43a007878f # Portfolio
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
