color: null
fieldLayouts:
  8b442c4f-2f43-4845-a1dc-632069d4f6c1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-31T07:58:14+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4b8b3f82-164b-414a-aa9a-cf0ffb30d28b
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-01-31T08:00:55+00:00'
            elementCondition: null
            fieldUid: 8749b82c-60bc-4bf2-bbc5-2887c2d8b826 # Dokument
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15eb012d-5e74-482e-a14f-2f6b6f0e9256
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: acd6e647-d061-486b-ab40-d498bdf9ae99
        userCondition: null
handle: downloads
hasTitleField: true
icon: ''
name: Downloads
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
