color: null
fieldLayouts:
  144f310e-05a5-4b81-8e54-52902a75d090:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-31T09:38:14+00:00'
            elementCondition: null
            fieldUid: ce51fadb-483c-4fc2-9160-7cf85ac48cad # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99dcb69e-f966-4e16-ba60-5815e5cf05d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-31T09:38:14+00:00'
            elementCondition: null
            fieldUid: b8e20bcc-ca90-457d-8a96-dc15a1ff10ee # Subline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee106344-88c4-4687-a2df-32da7533d569
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-31T09:38:14+00:00'
            elementCondition: null
            fieldUid: 7a09aaed-d19d-4ede-b382-6f23bce5a0ca # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7f49a82-8351-4021-978c-90de2796c058
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8379b0a9-65a4-4767-b682-a55230b87ef9
        userCondition: null
handle: exams
hasTitleField: false
icon: ''
name: Prüfungen
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
