color: null
fieldLayouts:
  f855fd4f-80f2-421b-9fc3-dcc46bb0ab5d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-31T09:41:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e63836ac-2eba-4615-87c1-c7c34acc29aa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-31T09:45:50+00:00'
            elementCondition: null
            fieldUid: 7a09aaed-d19d-4ede-b382-6f23bce5a0ca # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff4f2d9f-adbe-4081-a3e1-c447c098dcd2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6a170c6b-7c7c-4f6b-bc03-aff50dcafcf7
        userCondition: null
handle: examsSingles
hasTitleField: true
icon: ''
name: Prüfungen
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
