fieldLayouts:
  d60d7a13-bec5-487e-b145-041be105b9d1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6fbab8f3-9270-4716-890a-4c52dd100d2b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 32e9b2eb-4f11-42f0-830a-f778253566a0 # text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c167c1a-e251-4911-b2b1-c12bb96ba580
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: e41d2a47-1364-4706-a953-aa1b8bd56d3e
        userCondition: null
handle: imprint
hasTitleField: true
name: Impressum
section: abe89ac8-438d-4fe3-acf3-f816dcdfbd6e # Impressum
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
