color: null
fieldLayouts:
  4cb15fc0-649c-481e-bd8c-dd2f28bbf6df:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cf4769d8-2e9c-4092-b448-a281a2c406bb
            handle: null
            includeInCards: true
            instructions: null
            label: Headline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d43b031b-d776-413d-8463-a35167205999
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e4fc67e5-1248-4164-adce-fc6dea4bed0c
            handle: paddingTop
            includeInCards: false
            instructions: null
            label: 'Padding top'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7b0a6c6-8512-4de3-ac5a-5415986c04ec
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0a9f0664-5623-4180-a2ed-6954f31d9596
            handle: paddingBottom
            includeInCards: false
            instructions: null
            label: 'Padding Bottom'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b4361e0-a0c7-4bc5-bdd0-06f5df6c1d07
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 994f8cde-a1b1-4f82-aaa2-84c40ca53a25
        userCondition: null
handle: moduleHeadline
hasTitleField: false
icon: null
name: Headline
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
