color: null
fieldLayouts:
  541741c3-6401-4c0f-910d-b30d9ab5532b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 88f24a34-4ebc-4bf2-b615-1d432547918a
            handle: null
            includeInCards: false
            instructions: null
            label: Bild
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 739d0a60-244d-4a71-bceb-fc7577281d3d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4adfd44c-695c-434a-85d5-974eda9a3b97
            handle: paddingTop
            includeInCards: true
            instructions: null
            label: 'Padding Top'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62ff0054-eaf4-44f0-a514-9b7b4e065516
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cee2892e-09a0-46fc-ac6a-0ee40419f6a3
            handle: paddingBottom
            includeInCards: false
            instructions: null
            label: 'Padding Bottom'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 314bbec3-0470-44b5-9124-6714fa7897b8
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 604aa978-b38f-4ac2-84f0-46954c645dbb
        userCondition: null
handle: moduleImage
hasTitleField: false
icon: null
name: Bild
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
