color: null
fieldLayouts:
  99cf43e9-7000-42eb-9d4b-191a58212ea7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bb54d838-09fe-4083-8116-a503684a87e2
            handle: null
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8674b69-30c3-440b-a4b7-5603cc1eee53
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ef1162f4-9ab1-4c07-ba05-097fac7582b3
            handle: null
            includeInCards: false
            instructions: null
            label: 'Padding Top'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec65aa96-ec4e-44a8-ad1d-0d92bd2500c0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cef17153-828d-491f-bc13-0c4448e870df
            handle: null
            includeInCards: false
            instructions: null
            label: 'Padding Bottom'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bf82008-1a57-431d-84bc-b29495e57cdb
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 691840b1-6d38-4417-9c9f-828a071dd846
        userCondition: null
handle: moduleText
hasTitleField: false
icon: null
name: Text
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
