color: null
fieldLayouts:
  fd5f5985-ee7f-4f09-8b2e-ff953ebe5ba4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-11T15:27:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5f5bdd8f-6bc1-49c8-825b-6fb9fce91e1c
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-01-24T08:53:14+00:00'
            elementCondition: null
            fieldUid: cde20e84-eb8a-4bd9-bb93-2d53c03e54eb # Hero Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2510c09-2e0d-4ec8-a0ec-751e64048401
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-01-24T08:53:14+00:00'
            elementCondition: null
            fieldUid: 7a09aaed-d19d-4ede-b382-6f23bce5a0ca # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01ee8931-6c95-4345-adcd-68d9c13e2010
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a662c8af-03c0-4568-9598-17c4ef69d2e8
        userCondition: null
handle: newsEntry
hasTitleField: true
icon: ''
name: Aktuelles
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
