color: null
fieldLayouts:
  f30ab80d-3a4d-4986-8568-de06f32e3bc4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-11T15:17:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ed159906-d68e-4ffb-9e99-a83ca22ac521
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 337a91cf-ab79-440a-aa54-e90daf67064a
        userCondition: null
handle: news
hasTitleField: true
icon: ''
name: Aktuelles
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
