fieldLayouts:
  6f647fdb-0f1e-4ccb-a360-d9ef72fe9b35:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 30203fae-5c7f-4c9a-99dd-ee65c624f594
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 32e9b2eb-4f11-42f0-830a-f778253566a0 # text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a999cd9-c976-4673-b67e-91429e574d83
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: d1eef98a-2020-45fd-ace3-31b7a9d072ed
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3494d0db-46d9-4ef4-b39d-4a5786b70db7 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66648fb5-b38c-4b67-8924-852eae4006b4
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 3b235987-ecbd-48c8-ae37-b2166e78c961
        userCondition: null
handle: privacy
hasTitleField: true
name: Datenschutz
section: 3066e6a4-a59c-4300-9af3-c66387323f7e # Datenschutz
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
