color: fuchsia
fieldLayouts:
  9fcca74f-4ea8-4891-b189-f5b91a9a986e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4cc24601-07e6-4dd7-9583-7078fe64623f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4990761b-1b15-4092-9905-ebdda0697aeb # Hero Subline
            handle: null
            includeInCards: false
            instructions: null
            label: 'Projekt Subline'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0335e5e-4ee8-4561-978f-09ef69bb7698
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1eb88eb9-dc8e-4f62-a756-a0f68f2c4b56 # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b6bd9eb-45c1-48b9-8088-c7e59bcc6720
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 685df29e-e1b5-4b31-9289-037d21fe22b9
            userCondition: null
          -
            elementCondition: null
            fieldUid: 73e0ab0e-42a5-4ce0-bdea-00f683581801 # Dienstleistung
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18decfde-0548-47fc-80eb-ca9308a32780
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1dfacd29-1553-497b-bafc-e77dae9cde56 # Vorschaubild
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 147c016b-5633-4269-8b97-45f4111131d6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e7ee8b3a-be5d-47ce-b17d-cd53242423a9 # Blog Autor
            handle: null
            includeInCards: false
            instructions: null
            label: Künstler
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d42d19e-7dc8-4f0e-8a2b-9afc891945f7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cc625440-3f00-4589-8641-1066da038ff5 # Kunde
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e009ac5e-717d-4088-a3af-68191a222e8b
            userCondition: null
            warning: null
            width: 50
        name: Inhalt
        uid: f84c00dd-4789-45cb-807e-39a372c12c19
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 36fcb770-0e73-4e62-b21a-adbfcef75309 # Pagebuilder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50fda19d-05ff-4598-aa2b-5966f8d9c514
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 31963ba0-e84e-4b22-acbd-35e1eb54921b
        userCondition: null
handle: projectStandard
hasTitleField: true
icon: banana
name: Projekt
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
