color: null
fieldLayouts:
  33017de1-224b-432e-bd1d-123e26e49a1b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-11T15:24:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 34f28556-3770-405e-93cd-9490ec5dde12
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-12-11T15:39:13+00:00'
            elementCondition: null
            fieldUid: cf27a32b-d23f-4ee3-a52f-09465c833f30 # Nav Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26ceb963-abf2-49e7-aefe-ea678f53e209
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-12-11T15:40:19+00:00'
            elementCondition: null
            fieldUid: 1fecbeb4-dfb3-4886-82ce-08ca8ee9cfaa # Nav Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a8d2329-8f1e-48bb-965e-9713c9a529de
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d07df437-74d8-4763-b44f-b5656df2ce12
        userCondition: null
handle: quickNavigation
hasTitleField: true
icon: ''
name: 'Quick Menü'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
