color: null
fieldLayouts:
  7c3f53a8-778b-4565-b4ff-f1570c433146:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-11T15:19:20+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 00659ce3-8657-410c-bbd0-dcd62e60f33b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9ebf2354-185e-43ba-99d3-0a2cc27bdc7e
        userCondition: null
handle: service
hasTitleField: true
icon: ''
name: Service
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
