color: null
fieldLayouts:
  7c3f53a8-778b-4565-b4ff-f1570c433146:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-31T08:03:56+00:00'
            elementCondition: null
            fieldUid: ce51fadb-483c-4fc2-9160-7cf85ac48cad # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a3d0b00-a092-4e04-a779-d17aa4a0002a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-31T08:03:56+00:00'
            elementCondition: null
            fieldUid: b8e20bcc-ca90-457d-8a96-dc15a1ff10ee # Subline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30d71017-54b2-44be-a35c-216c707fcbc1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-31T08:03:56+00:00'
            elementCondition: null
            fieldUid: 7a09aaed-d19d-4ede-b382-6f23bce5a0ca # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fc8e002-2230-4fca-9f07-08311ac2dd89
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1c15a910-0df2-4122-a335-9c0ed46ec61f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-31T08:06:57+00:00'
            elementCondition: null
            template: _controlpanel/_service-link.twig
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: aed4dd27-89ec-4ab6-8be9-91db9a7b1185
            userCondition: null
            width: 100
        name: Downloads
        uid: 27c8b859-941d-4796-96f6-d9158c4efa84
        userCondition: null
handle: service
hasTitleField: false
icon: ''
name: Service
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
