color: null
fieldLayouts:
  2b8cc162-87ff-4b3e-877a-70e71ac4b961:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 94402de0-7ebe-4490-b69b-642b79840902
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d80dbe4-bb3b-4248-8d0e-dc85789145ba # Portraitfoto
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21604313-35c8-4111-88c8-729c230319ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2876dd87-48d7-449a-a4d1-d9702c959595 # Subline zum Teammitglied
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cce2e137-96fb-41e0-8aa2-8d51521f8f12
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 354c00ae-bedd-49fa-8c36-fb631c82a20a # Skills
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1d27afb-0408-4974-baad-32492c149aa8
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 94341283-047b-4534-ae4c-5a74e3f468c0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f5c36f37-2100-43b7-b63b-7e40a3ce5c36 # Straße + Hausnummer
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55eed4fe-d183-4556-875e-f38402bf3f36
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c7696060-de57-4ba4-8bca-1ae2954705c2 # Ort
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96f52a97-384f-4bb2-99d7-2fec884a2064
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 92ffb374-b480-4587-b176-8c9564330ed9
            userCondition: null
          -
            elementCondition: null
            fieldUid: 4903f9fb-d73b-41f2-bcc2-d9c4edf40aa9 # Mail
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11c77eff-8448-4cb5-9f47-45d0d6668377
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2b376b85-fe59-4b60-818b-853416605735 # Telefonnummer
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fac75adc-fd94-44ae-80cb-b5e4acbde023
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4a9472b4-14a2-4642-b0d4-1715ae07df0e # Webseite
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17538f55-3549-480a-bc8f-baf7d98c111d
            userCondition: null
            warning: null
            width: 100
        name: Kontakt
        uid: cf3be5bb-55e2-490c-b044-e1a5147dba0a
        userCondition: null
handle: teamMemberBasic
hasTitleField: true
icon: ''
name: 'Team Member (Basic)'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: none
