field: 36fcb770-0e73-4e62-b21a-adbfcef75309 # Pagebuilder
fieldLayouts:
  4cb15fc0-649c-481e-bd8c-dd2f28bbf6df:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cf4769d8-2e9c-4092-b448-a281a2c406bb # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d43b031b-d776-413d-8463-a35167205999
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e4fc67e5-1248-4164-adce-fc6dea4bed0c # Padding top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7b0a6c6-8512-4de3-ac5a-5415986c04ec
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 0a9f0664-5623-4180-a2ed-6954f31d9596 # Padding Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b4361e0-a0c7-4bc5-bdd0-06f5df6c1d07
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 994f8cde-a1b1-4f82-aaa2-84c40ca53a25
        userCondition: null
fields:
  0a9f0664-5623-4180-a2ed-6954f31d9596: # Padding Bottom
    columnSuffix: ccsbqxbb
    contentColumnType: string
    fieldGroup: null
    handle: paddingBottom
    instructions: null
    name: 'Padding Bottom'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - '8'
            -
              - value
              - '8'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '16'
            -
              - value
              - '16'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '32'
            -
              - value
              - '32'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '48'
            -
              - value
              - '48'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '64'
            -
              - value
              - '64'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  cf4769d8-2e9c-4092-b448-a281a2c406bb: # Headline
    columnSuffix: icytvahm
    contentColumnType: text
    fieldGroup: null
    handle: moduleheadline
    instructions: null
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e4fc67e5-1248-4164-adce-fc6dea4bed0c: # Padding top
    columnSuffix: sgpvkfzp
    contentColumnType: string
    fieldGroup: null
    handle: paddingTop
    instructions: null
    name: 'Padding top'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - '8'
            -
              - value
              - '8'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '16'
            -
              - value
              - '16'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '32'
            -
              - value
              - '32'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '48'
            -
              - value
              - '48'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '64'
            -
              - value
              - '64'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: moduleHeadline
name: Headline
sortOrder: 1
