field: 36fcb770-0e73-4e62-b21a-adbfcef75309 # Pagebuilder
fieldLayouts:
  99cf43e9-7000-42eb-9d4b-191a58212ea7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bb54d838-09fe-4083-8116-a503684a87e2 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8674b69-30c3-440b-a4b7-5603cc1eee53
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ef1162f4-9ab1-4c07-ba05-097fac7582b3 # Padding Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec65aa96-ec4e-44a8-ad1d-0d92bd2500c0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cef17153-828d-491f-bc13-0c4448e870df # Padding Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bf82008-1a57-431d-84bc-b29495e57cdb
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 691840b1-6d38-4417-9c9f-828a071dd846
        userCondition: null
fields:
  bb54d838-09fe-4083-8116-a503684a87e2: # Text
    columnSuffix: ulgkuewh
    contentColumnType: text
    fieldGroup: null
    handle: moduleText
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  cef17153-828d-491f-bc13-0c4448e870df: # Padding Bottom
    columnSuffix: skbubtaw
    contentColumnType: string
    fieldGroup: null
    handle: paddingBottom
    instructions: null
    name: 'Padding Bottom'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - '8'
            -
              - value
              - '8'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '16'
            -
              - value
              - '16'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '32'
            -
              - value
              - '32'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '48'
            -
              - value
              - '48'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '64'
            -
              - value
              - '64'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  ef1162f4-9ab1-4c07-ba05-097fac7582b3: # Padding Top
    columnSuffix: ftiofvmc
    contentColumnType: string
    fieldGroup: null
    handle: paddingTop
    instructions: null
    name: 'Padding Top'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - '8'
            -
              - value
              - '8'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '16'
            -
              - value
              - '16'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '32'
            -
              - value
              - '32'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '48'
            -
              - value
              - '48'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '64'
            -
              - value
              - '64'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: moduleText
name: Text
sortOrder: 2
