field: 36fcb770-0e73-4e62-b21a-adbfcef75309 # Pagebuilder
fieldLayouts:
  541741c3-6401-4c0f-910d-b30d9ab5532b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 88f24a34-4ebc-4bf2-b615-1d432547918a # Bild
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 739d0a60-244d-4a71-bceb-fc7577281d3d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4adfd44c-695c-434a-85d5-974eda9a3b97 # Padding Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62ff0054-eaf4-44f0-a514-9b7b4e065516
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cee2892e-09a0-46fc-ac6a-0ee40419f6a3 # Padding Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 314bbec3-0470-44b5-9124-6714fa7897b8
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 604aa978-b38f-4ac2-84f0-46954c645dbb
        userCondition: null
fields:
  4adfd44c-695c-434a-85d5-974eda9a3b97: # Padding Top
    columnSuffix: yiyefazw
    contentColumnType: string
    fieldGroup: null
    handle: paddingTop
    instructions: null
    name: 'Padding Top'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - '8'
            -
              - value
              - '8'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '16'
            -
              - value
              - '16'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '32'
            -
              - value
              - '32'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '48'
            -
              - value
              - '48'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '64'
            -
              - value
              - '64'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  88f24a34-4ebc-4bf2-b615-1d432547918a: # Bild
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: moduleImage
    instructions: null
    name: Bild
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: true
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:227252fb-a26f-42b6-ae49-f1e8f6a82c86' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: pagebuilder
      restrictedLocationSource: 'volume:227252fb-a26f-42b6-ae49-f1e8f6a82c86' # Images
      restrictedLocationSubpath: pagebuilder
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:227252fb-a26f-42b6-ae49-f1e8f6a82c86' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  cee2892e-09a0-46fc-ac6a-0ee40419f6a3: # Padding Bottom
    columnSuffix: cqtjgujd
    contentColumnType: string
    fieldGroup: null
    handle: paddingBottom
    instructions: null
    name: 'Padding Bottom'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - '8'
            -
              - value
              - '8'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '16'
            -
              - value
              - '16'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '32'
            -
              - value
              - '32'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '48'
            -
              - value
              - '48'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '64'
            -
              - value
              - '64'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: moduleImage
name: Bild
sortOrder: 3
