columnSuffix: dcrpuqna
contentColumnType: boolean
handle: backgroundSwitch
instructions: null
name: Hintergrundfarbe
searchable: false
settings:
  default: false
  offLabel: hell
  onLabel: dunkel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
