columnSuffix: null
contentColumnType: string
handle: blogAuthor
instructions: null
name: 'Blog Autor'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:c2cd05e6-a83d-4c05-ba35-c7c61951cc78' # Team
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
