columnSuffix: null
handle: department
instructions: null
name: Abteilung
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  source: 'group:6e57c3b3-9e16-47c7-9a15-154c8d857b2d' # Abteilung/Personengruppe
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
