columnSuffix: rbrvdpse
contentColumnType: text
fieldGroup: 0cafd6b0-a390-4f26-8a65-1ac56dddc831 # _hero
handle: heroHeadline
instructions: null
name: 'Hero Headline'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
