columnSuffix: null
handle: highlightImage
instructions: null
name: Hot
searchable: false
settings:
  default: false
  offLabel: not
  onLabel: hot
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
