columnSuffix: gdrpjzfy
contentColumnType: text
fieldGroup: 0ec3fd07-a143-4155-839a-4ffd252ba245 # portfolio
handle: memberLocation
instructions: null
name: Ort
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
