columnSuffix: null
handle: navLink
instructions: null
name: 'Nav Link'
searchable: false
settings:
  maxLength: 255
  showLabelField: false
  showTargetField: true
  typeSettings:
    __assoc__:
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
  types:
    - url
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
