columnSuffix: skbubtaw
handle: paddingBottom
instructions: null
name: 'Pagebuilder - Text - Padding Bottom'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - '8'
        -
          - value
          - '8'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '16'
        -
          - value
          - '16'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '32'
        -
          - value
          - '32'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '48'
        -
          - value
          - '48'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '64'
        -
          - value
          - '64'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
