columnSuffix: null
contentColumnType: string
fieldGroup: 1c988a8a-03a4-48c6-9db8-24703e1dcb2c # __theme
handle: pagebuilder
instructions: null
name: Pagebuilder
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagebuilder}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
