columnSuffix: bmqqfvja
contentColumnType: boolean
handle: portfolioDetails
instructions: null
name: Details
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
