columnSuffix: srqikjog
contentColumnType: text
handle: sectionAboutUsText
instructions: null
name: 'Sektion - Über uns Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
