columnSuffix: vbuloxnf
contentColumnType: text
fieldGroup: e9bc973e-8620-4b72-adbd-cea8abf68075 # _global
handle: seoField
instructions: null
name: SEO
searchable: false
settings:
  description: 'Künstler- und Kreativgemeinschaft für Grafik, Foto, Video, Webdesign und Webentwicklung. Kreative Lösungen für Unternehmen aus Bayern und Deutschland.'
  hideSocial: '1'
  robots:
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
  socialImage:
    - '295'
  suffixAsPrefix: null
  title:
    -
      __assoc__:
        -
          - key
          - '1'
        -
          - locked
          - '0'
        -
          - template
          - '{title}'
    -
      __assoc__:
        -
          - key
          - '2'
        -
          - locked
          - '1'
        -
          - template
          - ' - {{ siteName }}'
  titleSuffix: null
translationKeyFormat: null
translationMethod: none
type: ether\seo\fields\SeoField
