columnSuffix: null
handle: serviceEntries
instructions: null
name: Dienstleistung
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: true
  showSiteMenu: false
  sources:
    - 'section:78940b12-1c99-4891-a34c-0ff8a86a5c8d' # Leistungen
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
