columnSuffix: ujutumwz
contentColumnType: text
handle: teamName
instructions: null
name: 'Name des Teammitglieds'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: 'Vor- und Nachname'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
