defaultPlacement: end
enableVersioning: true
entryTypes:
  - de3031a4-f0db-4fe2-97d0-a9f8a09ef4b2 # Prüfungen
handle: exams
maxAuthors: 1
name: Prüfungen
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  863842fc-9f19-4f63-97b0-ce8cdc0cf482: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _pages/exams.twig
    uriFormat: pruefungen
type: single
