defaultPlacement: beginning
enableVersioning: true
entryTypes:
  - 7ddfcaff-57ed-4171-b773-31654d8fb98a # Hauptmenü
handle: footerNav
maxAuthors: 1
name: 'Footer Service'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  863842fc-9f19-4f63-97b0-ce8cdc0cf482: # $SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 8101b723-8c79-4d7e-b422-4673100176a7
type: structure
