defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2fdbe1e7-a157-4eb6-8992-b787d9e6f07d # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  92fa6fe8-29b4-416b-97c9-1cbe33fd43e7: # $PEDRO_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _index_member.twig
    uriFormat: __home__
  fb08b855-3bf9-4c67-afe2-49291cae828f: # grafikbuam.
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
