defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  fb08b855-3bf9-4c67-afe2-49291cae828f: # grafikbuam.
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
