defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7ddfcaff-57ed-4171-b773-31654d8fb98a # Hauptmenü
handle: mainNavigation
maxAuthors: 1
name: Hauptmenü
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  863842fc-9f19-4f63-97b0-ce8cdc0cf482: # $SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: ee3f7316-47ab-4ca1-a5e0-61fcb90c35df
type: structure
