defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 35e33973-944b-4b51-9f27-cd93d0b3eaf0 # Aktuelles
handle: newsIndex
maxAuthors: 1
name: Aktuelles
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  863842fc-9f19-4f63-97b0-ce8cdc0cf482: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _pages/_news/index.twig
    uriFormat: aktuelles
type: single
