defaultPlacement: end
enableVersioning: true
entryTypes:
  - 70602d87-4fe4-4f22-9161-b35e824992ca # Datenschutz
handle: privacy
maxAuthors: 1
name: Datenschutz
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  92fa6fe8-29b4-416b-97c9-1cbe33fd43e7: # $PEDRO_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _pages/_default.twig
    uriFormat: datenschutz
  fb08b855-3bf9-4c67-afe2-49291cae828f: # grafikbuam.
    enabledByDefault: true
    hasUrls: true
    template: _pages/_default.twig
    uriFormat: datenschutz
type: single
