defaultPlacement: end
enableVersioning: true
entryTypes:
  - c72e9ef9-03ed-4887-a29a-0a517fbc7e04 # Team Member (Extern)
  - 2ce9cabf-ec24-4086-86c9-4cf1a29fe1d1 # Team Member (Basic)
handle: team
maxAuthors: 1
name: Team
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  92fa6fe8-29b4-416b-97c9-1cbe33fd43e7: # $PEDRO_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  fb08b855-3bf9-4c67-afe2-49291cae828f: # grafikbuam.
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 55e6607c-51fb-4756-b8bf-1dfe644dc1cb
type: structure
