defaultPlacement: beginning
fieldLayouts:
  bf0c649a-fc2b-47f6-82f7-dc2ae702d39b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-11T15:33:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 7afe3346-1b4c-49a3-b387-20e94a324822
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-01-28T11:21:32+00:00'
            elementCondition: null
            fieldUid: e60cec95-a25d-45ae-8c86-3d2a2cfbd160 # Portraitbild
            handle: null
            includeInCards: false
            instructions: null
            label: Gruppenbild
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c86e203a-ddf5-4c31-8bc4-7771dfb4023e
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-01-28T10:25:31+00:00'
            elementCondition: null
            fieldUid: 7a09aaed-d19d-4ede-b382-6f23bce5a0ca # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56495a76-530d-43d5-800c-1201439bd2b8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 04c69124-7bce-4787-9b19-552c925535f9
        userCondition: null
handle: department
name: Abteilung/Personengruppe
siteSettings:
  863842fc-9f19-4f63-97b0-ce8cdc0cf482: # $SITE_NAME
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: bb00e7db-8378-4016-8a65-85ccfb230805
