defaultPlacement: end
fieldLayouts:
  64d5262c-6092-4799-aa83-71c65143ff06:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 01c758e9-fc9d-4823-af22-e2c68e918428
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 94cdeda2-08b5-48f5-bd12-2b8bcb169232
        userCondition: null
handle: serviceCategory
name: Leistungskategorie
siteSettings:
  92fa6fe8-29b4-416b-97c9-1cbe33fd43e7: # $PEDRO_SITE_NAME
    hasUrls: false
    template: null
    uriFormat: null
  fb08b855-3bf9-4c67-afe2-49291cae828f: # grafikbuam.
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 45614071-8c15-4523-adcd-154ed5ef3f7e
