defaultPlacement: beginning
fieldLayouts:
  bf0c649a-fc2b-47f6-82f7-dc2ae702d39b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-11T15:33:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 7afe3346-1b4c-49a3-b387-20e94a324822
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 04c69124-7bce-4787-9b19-552c925535f9
        userCondition: null
handle: team
name: Team
siteSettings:
  863842fc-9f19-4f63-97b0-ce8cdc0cf482: # $SITE_NAME
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: bb00e7db-8378-4016-8a65-85ccfb230805
