fieldLayouts:
  28af0ffd-3ca3-42af-ad4c-b50b73eba3fe:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 0b83afb8-d577-418a-a6ad-c5b357ba9671
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: dcc50b50-a099-4425-8c3c-b242e764d5f4
        userCondition: null
handle: skills
name: Skills
